version: "3"

services:
  db:
    image: mysql:5.7
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3310:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
      - gem_data:/usr/local/bundle

  api:
    container_name: back
    tty: true
    depends_on:
      - db
    build:
      context: back/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./back:/app
    command: rails server -b 0.0.0.0

  front:
    build:
      context: front/
      dockerfile: Dockerfile
    container_name: web
    volumes:
      - ./front/app:/usr/src/app
    command: 'yarn dev'
    ports:
      - "4001:3000"

volumes:
  mysql-data:
    driver: local
  gem_data:
    driver: local