version: '3'
services:
  db:
    container_name: complete_catalogue_db
    image: postgres
    ports:
      - "5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
  backend:
    build:
      context: backend
      args:
        UID: ${UID:-1001}
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8080 -b '0.0.0.0'"
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    user: rails
  frontend:
    build:
      context: frontend
      args:
        UID: ${UID:-1001}
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3000:3000"
    user: frontend